### ISSUE TITLE
XSD for NatSpec Sentences XML

### ISSUE THREAD

**Issue by rstarke-dd** [iljabauer/quamo-wiki#1]
Specifies the structure of the xml that is created by the extractor in the local workspace and wich is then committed to the repository where it is read by the runner (on the build server).

**Comment by iljabauer** [comment]
The plan changed a little bit after talking to mseifert. NatSpec has the possibility to extract all known patterns and just pass it to xstream, it will generate the xml file with the pattern. Then in the Runner we have to parse the xml file and pass it to the NatSpec MatchService. We have to search if there is a NatSpec scenario for the running test case. If so, we have to pass it to the MatchService and it will return the matched sentences.
